name: dynoman # you probably want to 'snapcraft register <name>'
version: '1.0.0-SNAPSHOT' # just for humans, typically '1.2+git' or '1.3.2'
summary: DynamoDB management UI # 79 char long summary
description: |
  Desktop application to manage and query DynamoDB tables.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core18

architectures:
  - build-on: amd64

apps:
  dynoman:
    command: java -jar build/libs/dynoman-1.0.0-SNAPSHOT.jar
    plugs: [network, desktop]

parts:
  dynoman:
    #    after: [desktop-gtk3]
    source-type: local
    plugin: gradle
    source: .
    override-build: |
      ./gradlew shadowJar
    gradle-output-dir:
      build/libs
    build-packages:
      - openjdk-11-jdk
      - openjfx
